# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.6.0.post208+hcf4438d924e4 on Sun 17 Mar 2019 11:35:22 AM 
# Model: Coastal Vulnerability

import natcap.invest.coastal_vulnerability

import logging
import time
import os

LOGGER = logging.getLogger()
logging.basicConfig(level='INFO')

BASE_DATA = '/home/dmf/bahamas-mpa/cv/cv-fromjess/Bahamas_regionalCV_Inputs'
WORKSPACE_DIR = '/home/dmf/invest_dev/coastal_vulnerability/bahamas/'

args = {
    u'aoi_vector_path': os.path.join(BASE_DATA, 'AOI_Bahamas_IslandGroup/AOI_CV_Bahamaswide.shp'),
    u'dem_averaging_radius': u'2000',
    u'dem_path': os.path.join(BASE_DATA, 'Bahamas_SRTM11.tif'),
    u'geomorphology_fill_value': u'3',
    u'geomorphology_vector_path': os.path.join(BASE_DATA, 'Bahamas_Geomorphology_Final.shp'),
    u'habitat_table_path': os.path.join(BASE_DATA, 'NaturalHabitat_Bahamaswide_3_7.csv'),
    u'landmass_vector_path': os.path.join(BASE_DATA, 'LandPoly_Bahamas_08112017.shp'),
    u'max_fetch_distance': u'12000',
    u'model_resolution': u'500',
    u'results_suffix': u'',
    u'shelf_contour_vector_path': os.path.join(BASE_DATA, 'Bahamas_continentalshelf_UTM18N_line.shp'),
    u'workspace_dir': WORKSPACE_DIR,
    u'wwiii_vector_path': u'/home/dmf/invest-sample-data/CoastalProtection/Input/WaveWatchIII.shp',
    u'n_workers': '2',
}

if __name__ == '__main__':
    start = time.time()
    natcap.invest.coastal_vulnerability.execute(args)
    LOGGER.info(time.time() - start)
